apiVersion: v1
kind: ConfigMap
metadata:
  name: currency-exchange-config
  namespace: currency-exchange-prod
data:
  SPRING_PROFILES_ACTIVE: prod
  SERVER_PORT: "8080"
  SPRING_APPLICATION_NAME: currency-exchange-service-prod
  LOGGING_LEVEL_ROOT: INFO
  LOGGING_LEVEL_APP: DEBUG
  BUNDESBANK_API_URL: https://api.statistiken.bundesbank.de/rest
  SCHEDULER_CRON: "0 30 11 * * ?"
