apiVersion: v1
kind: Secret
metadata:
  name: currency-backend-secrets
  namespace: currency-backend-prod
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/currency_db_prod
  SPRING_DATASOURCE_USERNAME: prod_currency_user
  SPRING_DATASOURCE_PASSWORD: prod_currency_pass
  BUNDESBANK_API_KEY: prod-bundesbank-api-key
