apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: currency-backend-hpa
  namespace: currency-backend-uat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: currency-backend-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
