apiVersion: v1
kind: Service
metadata:
  name: currency-backend-service
  namespace: currency-backend-uat
spec:
  selector:
    app: currency-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
